port: 8080

db:
  host: "host.docker.internal"
  port: 5432
  username: "masha"
  dbname: "postgres"
  sslmode: "disable"
redis:
  host: "redis"
  addr: "localhost"
  port: 6379
  dbname: "session"
  password: "12345"
session:
  expiresAt: 1
